# Generated by Django 6.1 on 2026-08-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_assigned_at_resolved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='estimated_work_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
