# Generated by Django 6.1 on 2026-08-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_estimated_work_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_at',
        ),
        migrations.AddField(
            model_name='ticket',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
