# Generated by Django 6.1 on 2026-09-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_remove_ticket_assigned_at_ticket_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='branch',
            field=models.CharField(choices=[('RESISTENCIA', 'Resistencia'), ('CTES', 'Corrientes')], default='RESISTENCIA', max_length=20),
        ),
    ]
