# Generated by Django 6.1 on 2026-09-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='branch',
            field=models.CharField(choices=[('RESISTENCIA', 'Resistencia'), ('CTES', 'Corrientes'), ('ALL', 'Todas')], default='RESISTENCIA', max_length=20),
        ),
    ]
